spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:policy_finance}
    username: ${DB_USERNAME:policy_finance}
    password: ${DB_PASSWORD}
