CREATE TABLE financial_product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    max_amount NUMERIC(19, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_financial_product_code UNIQUE (code),
    CONSTRAINT ck_financial_product_max_amount_positive CHECK (max_amount > 0)
);

CREATE INDEX idx_financial_product_active_code
    ON financial_product (active, code);

CREATE TABLE product_rule_version (
    rule_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    interest_rate NUMERIC(7, 4) NOT NULL,
    repayment_months INTEGER NOT NULL,
    repayment_method VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_rule_version_product
        FOREIGN KEY (product_id) REFERENCES financial_product (product_id),
    CONSTRAINT uk_product_rule_version_product_version UNIQUE (product_id, version_no),
    CONSTRAINT ck_product_rule_version_version_positive CHECK (version_no > 0),
    CONSTRAINT ck_product_rule_version_valid_period CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT ck_product_rule_version_interest_rate_non_negative CHECK (interest_rate >= 0),
    CONSTRAINT ck_product_rule_version_repayment_months_positive CHECK (repayment_months > 0),
    CONSTRAINT ck_product_rule_version_repayment_method CHECK (repayment_method IN ('EQUAL_PAYMENT'))
);

CREATE INDEX idx_product_rule_version_product_period
    ON product_rule_version (product_id, valid_from, valid_to);

CREATE TABLE eligibility_rule (
    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version_id BIGINT NOT NULL,
    rule_type VARCHAR(40) NOT NULL,
    operator VARCHAR(30) NOT NULL,
    comparison_value VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT fk_eligibility_rule_version
        FOREIGN KEY (rule_version_id) REFERENCES product_rule_version (rule_version_id),
    CONSTRAINT ck_eligibility_rule_type CHECK (
        rule_type IN ('AGE', 'INCOME', 'CREDIT_SCORE', 'REGION', 'BUSINESS_PERIOD')
    ),
    CONSTRAINT ck_eligibility_rule_operator CHECK (
        operator IN ('GREATER_THAN_OR_EQUAL', 'LESS_THAN_OR_EQUAL', 'EQUAL', 'BETWEEN')
    )
);

CREATE INDEX idx_eligibility_rule_version_type
    ON eligibility_rule (rule_version_id, rule_type);
