CREATE TABLE customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_no VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    annual_income NUMERIC(19, 2) NOT NULL,
    credit_score INTEGER NOT NULL,
    region VARCHAR(50) NOT NULL,
    business_start_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_customer_customer_no UNIQUE (customer_no),
    CONSTRAINT ck_customer_annual_income_non_negative CHECK (annual_income >= 0),
    CONSTRAINT ck_customer_credit_score_range CHECK (credit_score BETWEEN 0 AND 1000)
);

CREATE TABLE application (
    application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    rule_version_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    requested_amount NUMERIC(19, 2) NOT NULL,
    received_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_application_customer
        FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
    CONSTRAINT fk_application_product
        FOREIGN KEY (product_id) REFERENCES financial_product (product_id),
    CONSTRAINT fk_application_rule_version
        FOREIGN KEY (rule_version_id) REFERENCES product_rule_version (rule_version_id),
    CONSTRAINT ck_application_status CHECK (
        status IN (
            'DRAFT', 'RECEIVED', 'ELIGIBILITY_CHECK', 'UNDER_REVIEW',
            'SUPPLEMENT_REQUESTED', 'APPROVED', 'REJECTED', 'EXECUTED',
            'REPAYING', 'REPAID', 'CLOSED'
        )
    ),
    CONSTRAINT ck_application_requested_amount_positive CHECK (requested_amount > 0)
);

CREATE INDEX idx_application_customer_received_at
    ON application (customer_id, received_at DESC);

CREATE INDEX idx_application_status_received_at
    ON application (status, received_at);

CREATE TABLE screening_result (
    screening_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    eligibility_rule_id BIGINT NOT NULL,
    passed BOOLEAN NOT NULL,
    reason VARCHAR(500) NOT NULL,
    checked_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_screening_result_application
        FOREIGN KEY (application_id) REFERENCES application (application_id),
    CONSTRAINT fk_screening_result_eligibility_rule
        FOREIGN KEY (eligibility_rule_id) REFERENCES eligibility_rule (rule_id)
);

CREATE INDEX idx_screening_result_application
    ON screening_result (application_id, screening_id);
