CREATE TABLE department (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_department_code UNIQUE (code)
);

CREATE TABLE employee (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    department_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_employee_no UNIQUE (employee_no),
    CONSTRAINT uk_employee_department_and_id UNIQUE (department_id, employee_id),
    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES department (department_id)
);

CREATE INDEX idx_employee_department_active
    ON employee (department_id, active);

CREATE TABLE application_assignment (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    assigned_by_employee_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL,
    released_at TIMESTAMPTZ,
    active BOOLEAN NOT NULL,
    reason VARCHAR(500) NOT NULL,
    CONSTRAINT fk_assignment_application
        FOREIGN KEY (application_id) REFERENCES application (application_id),
    CONSTRAINT fk_assignment_department
        FOREIGN KEY (department_id) REFERENCES department (department_id),
    CONSTRAINT fk_assignment_employee_department
        FOREIGN KEY (department_id, employee_id)
        REFERENCES employee (department_id, employee_id),
    CONSTRAINT fk_assignment_assigned_by
        FOREIGN KEY (assigned_by_employee_id) REFERENCES employee (employee_id),
    CONSTRAINT ck_assignment_release_time
        CHECK (released_at IS NULL OR released_at >= assigned_at),
    CONSTRAINT ck_assignment_active_release_consistency
        CHECK ((active = TRUE AND released_at IS NULL)
            OR (active = FALSE AND released_at IS NOT NULL))
);

CREATE UNIQUE INDEX uk_application_assignment_one_active
    ON application_assignment (application_id)
    WHERE active = TRUE;

CREATE INDEX idx_application_assignment_history
    ON application_assignment (application_id, assigned_at);

CREATE TABLE status_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    before_status VARCHAR(30) NOT NULL,
    after_status VARCHAR(30) NOT NULL,
    changed_by_employee_id BIGINT,
    changed_at TIMESTAMPTZ NOT NULL,
    reason VARCHAR(500) NOT NULL,
    CONSTRAINT fk_status_history_application
        FOREIGN KEY (application_id) REFERENCES application (application_id),
    CONSTRAINT fk_status_history_employee
        FOREIGN KEY (changed_by_employee_id) REFERENCES employee (employee_id),
    CONSTRAINT ck_status_history_before_status CHECK (
        before_status IN (
            'DRAFT', 'RECEIVED', 'ELIGIBILITY_CHECK', 'UNDER_REVIEW',
            'SUPPLEMENT_REQUESTED', 'APPROVED', 'REJECTED', 'EXECUTED',
            'REPAYING', 'REPAID', 'CLOSED'
        )
    ),
    CONSTRAINT ck_status_history_after_status CHECK (
        after_status IN (
            'DRAFT', 'RECEIVED', 'ELIGIBILITY_CHECK', 'UNDER_REVIEW',
            'SUPPLEMENT_REQUESTED', 'APPROVED', 'REJECTED', 'EXECUTED',
            'REPAYING', 'REPAID', 'CLOSED'
        )
    ),
    CONSTRAINT ck_status_history_changed CHECK (before_status <> after_status)
);

CREATE INDEX idx_status_history_application_changed_at
    ON status_history (application_id, changed_at);

CREATE TABLE application_review (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    comment VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_application_review_application
        FOREIGN KEY (application_id) REFERENCES application (application_id),
    CONSTRAINT fk_application_review_employee
        FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    CONSTRAINT ck_application_review_action CHECK (
        action IN (
            'REVIEW_STARTED', 'SUPPLEMENT_REQUESTED', 'REVIEW_RESUMED',
            'APPROVED', 'REJECTED'
        )
    )
);

CREATE INDEX idx_application_review_application_created_at
    ON application_review (application_id, created_at);
