CREATE TABLE loan (
    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    principal NUMERIC(19, 2) NOT NULL,
    outstanding_balance NUMERIC(19, 2) NOT NULL,
    interest_rate NUMERIC(7, 4) NOT NULL,
    executed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_loan_application UNIQUE (application_id),
    CONSTRAINT fk_loan_application
        FOREIGN KEY (application_id) REFERENCES application (application_id),
    CONSTRAINT ck_loan_principal_positive CHECK (principal > 0),
    CONSTRAINT ck_loan_outstanding_balance_range
        CHECK (outstanding_balance >= 0 AND outstanding_balance <= principal),
    CONSTRAINT ck_loan_interest_rate_non_negative CHECK (interest_rate >= 0)
);
